import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <div style={{marginBottom: '30px'}}>
                    Здесь располагается главная страница
                </div>
                <div>
                    Ссылки

                    <p><Link href={'/services'}><a>services</a></Link></p>
                    <p><Link href={'/services/1'}><a>services/1</a></Link></p>

                </div>
            </main>

        </div>
    )
}
